exclude: "docs|.git"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
        args: [dev-requirements.txt]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        language: python
        language_version: python3.10
        types_or: [python, pyi]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        language_version: python3.10
        types: [python]

  - repo: local
    hooks:
      - id: test
        name: test
        entry: pytest
        always_run: true
        pass_filenames: false
        language: python
        language_version: python3.10
        types: [python]
        additional_dependencies: [pytest==7.1.2]
